// <auto-generated />
using System;
using GestionIntApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestionIntApi.Migrations
{
    [DbContext(typeof(SistemaGestionDBcontext))]
    [Migration("20260102080632_nuevastablas")]
    partial class nuevastablas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestionIntApi.Models.Admin.MenuAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Icono")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MenusAdmin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icono = "dashboard",
                            Nombre = "Dashboard",
                            Url = "panel-control"
                        },
                        new
                        {
                            Id = 2,
                            Icono = "admin_panel_settings",
                            Nombre = "Usuarios Admin",
                            Url = "gestion-administradores"
                        },
                        new
                        {
                            Id = 3,
                            Icono = "how_to_reg",
                            Nombre = "Registro App Móvil",
                            Url = "registro-usuarios-app/nuevo"
                        },
                        new
                        {
                            Id = 4,
                            Icono = "payments",
                            Nombre = "Pagos",
                            Url = "gestion-pagos"
                        },
                        new
                        {
                            Id = 5,
                            Icono = "location_on",
                            Nombre = "Ubicación",
                            Url = "geolocalizacion-tiendas"
                        },
                        new
                        {
                            Id = 6,
                            Icono = "inventory",
                            Nombre = "Registrar Bodega",
                            Url = "inventario/registro-bodega"
                        },
                        new
                        {
                            Id = 7,
                            Icono = "edit_attributes",
                            Nombre = "Editar Bodega",
                            Url = "inventario/configuracion-bodega"
                        },
                        new
                        {
                            Id = 8,
                            Icono = "storefront",
                            Nombre = "Registrar Tienda",
                            Url = "gestion-tiendas/nueva-sucursal"
                        },
                        new
                        {
                            Id = 9,
                            Icono = "history",
                            Nombre = "Movimientos",
                            Url = "historial-movimientos"
                        },
                        new
                        {
                            Id = 10,
                            Icono = "assessment",
                            Nombre = "Reportes",
                            Url = "reportes-generales"
                        });
                });

            modelBuilder.Entity("GestionIntApi.Models.Admin.MenuRolAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("MenuAdminId")
                        .HasColumnType("integer");

                    b.Property<int?>("RolAdminId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MenuAdminId");

                    b.HasIndex("RolAdminId");

                    b.ToTable("MenuRolAdmin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MenuAdminId = 1,
                            RolAdminId = 1
                        },
                        new
                        {
                            Id = 2,
                            MenuAdminId = 2,
                            RolAdminId = 1
                        },
                        new
                        {
                            Id = 3,
                            MenuAdminId = 3,
                            RolAdminId = 1
                        },
                        new
                        {
                            Id = 4,
                            MenuAdminId = 4,
                            RolAdminId = 1
                        },
                        new
                        {
                            Id = 5,
                            MenuAdminId = 5,
                            RolAdminId = 1
                        },
                        new
                        {
                            Id = 6,
                            MenuAdminId = 6,
                            RolAdminId = 1
                        },
                        new
                        {
                            Id = 7,
                            MenuAdminId = 7,
                            RolAdminId = 1
                        },
                        new
                        {
                            Id = 8,
                            MenuAdminId = 8,
                            RolAdminId = 1
                        },
                        new
                        {
                            Id = 9,
                            MenuAdminId = 9,
                            RolAdminId = 1
                        },
                        new
                        {
                            Id = 10,
                            MenuAdminId = 10,
                            RolAdminId = 1
                        },
                        new
                        {
                            Id = 11,
                            MenuAdminId = 1,
                            RolAdminId = 3
                        },
                        new
                        {
                            Id = 12,
                            MenuAdminId = 3,
                            RolAdminId = 3
                        },
                        new
                        {
                            Id = 13,
                            MenuAdminId = 4,
                            RolAdminId = 3
                        },
                        new
                        {
                            Id = 14,
                            MenuAdminId = 6,
                            RolAdminId = 3
                        },
                        new
                        {
                            Id = 15,
                            MenuAdminId = 8,
                            RolAdminId = 3
                        },
                        new
                        {
                            Id = 16,
                            MenuAdminId = 9,
                            RolAdminId = 3
                        },
                        new
                        {
                            Id = 17,
                            MenuAdminId = 10,
                            RolAdminId = 3
                        });
                });

            modelBuilder.Entity("GestionIntApi.Models.Admin.MovimientoInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("MontoVenta")
                        .HasColumnType("numeric");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<int?>("TiendaDestinoId")
                        .HasColumnType("integer");

                    b.Property<int?>("TiendaOrigenId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UsuarioRegistro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("TiendaDestinoId");

                    b.HasIndex("TiendaOrigenId");

                    b.ToTable("MovimientosInventario");
                });

            modelBuilder.Entity("GestionIntApi.Models.Admin.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IMEI")
                        .HasColumnType("text");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioCompra")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PrecioVenta")
                        .HasColumnType("numeric");

                    b.Property<string>("Serie")
                        .HasColumnType("text");

                    b.Property<string>("Tamano")
                        .HasColumnType("text");

                    b.Property<int?>("TiendaId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoProducto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TiendaId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("GestionIntApi.Models.Admin.RolAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("RolesAdmin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Administrador",
                            FechaRegistro = new DateTime(2025, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Cliente",
                            FechaRegistro = new DateTime(2025, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Cajera",
                            FechaRegistro = new DateTime(2025, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("GestionIntApi.Models.Admin.UsuarioAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .HasColumnType("text");

                    b.Property<bool?>("EsActivo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreApellidos")
                        .HasColumnType("text");

                    b.Property<int?>("RolAdminId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RolAdminId");

                    b.ToTable("UsuariosAdmin");
                });

            modelBuilder.Entity("GestionIntApi.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DetalleClienteID")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DetalleClienteID")
                        .IsUnique();

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("GestionIntApi.Models.Credito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AbonadoCuota")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AbonadoTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Capacidad")
                        .HasColumnType("numeric");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DiaPago")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Entrada")
                        .HasColumnType("numeric");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoCuota")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FrecuenciaPago")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IMEI")
                        .HasColumnType("text");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MetodoPago")
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MontoPendiente")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("numeric");

                    b.Property<string>("NombrePropietario")
                        .HasColumnType("text");

                    b.Property<int>("PlazoCuotas")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ProximaCuota")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TiendaAppId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoProducto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalPagar")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorPorCuota")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("TiendaAppId");

                    b.ToTable("Creditos");
                });

            modelBuilder.Entity("GestionIntApi.Models.DetalleCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreApellidos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroCedula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DetallesCliente");
                });

            modelBuilder.Entity("GestionIntApi.Models.EmailSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("EmailSettings");
                });

            modelBuilder.Entity("GestionIntApi.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Icono")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icono = "dashboard",
                            Nombre = "DashBoard",
                            Url = "/pages/dashboard"
                        },
                        new
                        {
                            Id = 2,
                            Icono = "payments",
                            Nombre = "Pagos",
                            Url = "/pages/pagos"
                        },
                        new
                        {
                            Id = 3,
                            Icono = "person",
                            Nombre = "Usuario App",
                            Url = "/pages/usuarioApp"
                        },
                        new
                        {
                            Id = 4,
                            Icono = "admin_panel_settings",
                            Nombre = "Usuario Admin",
                            Url = "/pages/usuarioAdmin"
                        },
                        new
                        {
                            Id = 5,
                            Icono = "inventory",
                            Nombre = "Registrar Bodega",
                            Url = "/pages/bodega/registrar"
                        },
                        new
                        {
                            Id = 6,
                            Icono = "edit_attributes",
                            Nombre = "Editar Bodega",
                            Url = "/pages/bodega/editar"
                        },
                        new
                        {
                            Id = 7,
                            Icono = "storefront",
                            Nombre = "Registrar Tienda",
                            Url = "/pages/tienda/registrar"
                        },
                        new
                        {
                            Id = 8,
                            Icono = "history",
                            Nombre = "Movimientos",
                            Url = "/pages/movimientos"
                        },
                        new
                        {
                            Id = 9,
                            Icono = "assessment",
                            Nombre = "Reportes",
                            Url = "/pages/reportes"
                        },
                        new
                        {
                            Id = 10,
                            Icono = "location_on",
                            Nombre = "Ubicacion",
                            Url = "/pages/ubicacion"
                        });
                });

            modelBuilder.Entity("GestionIntApi.Models.MenuRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("MenuId")
                        .HasColumnType("integer");

                    b.Property<int?>("RolId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("RolId");

                    b.ToTable("MenuRols");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MenuId = 1,
                            RolId = 1
                        },
                        new
                        {
                            Id = 2,
                            MenuId = 2,
                            RolId = 1
                        },
                        new
                        {
                            Id = 3,
                            MenuId = 3,
                            RolId = 1
                        },
                        new
                        {
                            Id = 4,
                            MenuId = 4,
                            RolId = 1
                        },
                        new
                        {
                            Id = 5,
                            MenuId = 5,
                            RolId = 1
                        },
                        new
                        {
                            Id = 6,
                            MenuId = 6,
                            RolId = 1
                        },
                        new
                        {
                            Id = 7,
                            MenuId = 7,
                            RolId = 1
                        },
                        new
                        {
                            Id = 8,
                            MenuId = 8,
                            RolId = 1
                        },
                        new
                        {
                            Id = 9,
                            MenuId = 9,
                            RolId = 1
                        },
                        new
                        {
                            Id = 10,
                            MenuId = 10,
                            RolId = 1
                        },
                        new
                        {
                            Id = 11,
                            MenuId = 1,
                            RolId = 3
                        },
                        new
                        {
                            Id = 12,
                            MenuId = 2,
                            RolId = 3
                        },
                        new
                        {
                            Id = 13,
                            MenuId = 3,
                            RolId = 3
                        },
                        new
                        {
                            Id = 14,
                            MenuId = 5,
                            RolId = 3
                        },
                        new
                        {
                            Id = 15,
                            MenuId = 7,
                            RolId = 3
                        },
                        new
                        {
                            Id = 16,
                            MenuId = 8,
                            RolId = 3
                        },
                        new
                        {
                            Id = 17,
                            MenuId = 9,
                            RolId = 3
                        });
                });

            modelBuilder.Entity("GestionIntApi.Models.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Leida")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Notificacions");
                });

            modelBuilder.Entity("GestionIntApi.Models.RegistrarPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreditoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CreditoId");

                    b.ToTable("RegistrosPagos");
                });

            modelBuilder.Entity("GestionIntApi.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Rol");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Administrador",
                            FechaRegistro = new DateTime(2025, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Cliente",
                            FechaRegistro = new DateTime(2025, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Cajera",
                            FechaRegistro = new DateTime(2025, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("GestionIntApi.Models.Tienda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CedulaEncargado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreEncargado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreTienda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tiendas");
                });

            modelBuilder.Entity("GestionIntApi.Models.TiendaApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CedulaEncargado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("EstadoDeComision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TiendaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("TiendaId");

                    b.ToTable("TiendaApps");
                });

            modelBuilder.Entity("GestionIntApi.Models.Ubicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Ubicacions");
                });

            modelBuilder.Entity("GestionIntApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .HasColumnType("text");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreApellidos")
                        .HasColumnType("text");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RolId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GestionIntApi.Models.VerificationCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Expira")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("VerificationCode");
                });

            modelBuilder.Entity("GestionIntApi.Models.Admin.MenuRolAdmin", b =>
                {
                    b.HasOne("GestionIntApi.Models.Admin.MenuAdmin", "MenuAdmin")
                        .WithMany("MenuRolAdmins")
                        .HasForeignKey("MenuAdminId");

                    b.HasOne("GestionIntApi.Models.Admin.RolAdmin", "RolAdmin")
                        .WithMany("MenuRolAdmins")
                        .HasForeignKey("RolAdminId");

                    b.Navigation("MenuAdmin");

                    b.Navigation("RolAdmin");
                });

            modelBuilder.Entity("GestionIntApi.Models.Admin.MovimientoInventario", b =>
                {
                    b.HasOne("GestionIntApi.Models.Admin.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionIntApi.Models.Tienda", "TiendaDestino")
                        .WithMany()
                        .HasForeignKey("TiendaDestinoId");

                    b.HasOne("GestionIntApi.Models.Tienda", "TiendaOrigen")
                        .WithMany()
                        .HasForeignKey("TiendaOrigenId");

                    b.Navigation("Producto");

                    b.Navigation("TiendaDestino");

                    b.Navigation("TiendaOrigen");
                });

            modelBuilder.Entity("GestionIntApi.Models.Admin.Producto", b =>
                {
                    b.HasOne("GestionIntApi.Models.Tienda", "Tienda")
                        .WithMany("ProductosActuales")
                        .HasForeignKey("TiendaId");

                    b.Navigation("Tienda");
                });

            modelBuilder.Entity("GestionIntApi.Models.Admin.UsuarioAdmin", b =>
                {
                    b.HasOne("GestionIntApi.Models.Admin.RolAdmin", "RolAdmin")
                        .WithMany("UsuarioAdmins")
                        .HasForeignKey("RolAdminId");

                    b.Navigation("RolAdmin");
                });

            modelBuilder.Entity("GestionIntApi.Models.Cliente", b =>
                {
                    b.HasOne("GestionIntApi.Models.DetalleCliente", "DetalleCliente")
                        .WithOne("Cliente")
                        .HasForeignKey("GestionIntApi.Models.Cliente", "DetalleClienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionIntApi.Models.Usuario", "Usuario")
                        .WithOne("Cliente")
                        .HasForeignKey("GestionIntApi.Models.Cliente", "UsuarioId");

                    b.Navigation("DetalleCliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionIntApi.Models.Credito", b =>
                {
                    b.HasOne("GestionIntApi.Models.Cliente", "Cliente")
                        .WithMany("Creditos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionIntApi.Models.TiendaApp", "TiendaApp")
                        .WithMany()
                        .HasForeignKey("TiendaAppId");

                    b.Navigation("Cliente");

                    b.Navigation("TiendaApp");
                });

            modelBuilder.Entity("GestionIntApi.Models.MenuRol", b =>
                {
                    b.HasOne("GestionIntApi.Models.Menu", "Menu")
                        .WithMany("MenuRols")
                        .HasForeignKey("MenuId");

                    b.HasOne("GestionIntApi.Models.Rol", "Rol")
                        .WithMany("MenuRols")
                        .HasForeignKey("RolId");

                    b.Navigation("Menu");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("GestionIntApi.Models.Notificacion", b =>
                {
                    b.HasOne("GestionIntApi.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("GestionIntApi.Models.RegistrarPago", b =>
                {
                    b.HasOne("GestionIntApi.Models.Credito", "Credito")
                        .WithMany("RegistrosPagos")
                        .HasForeignKey("CreditoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credito");
                });

            modelBuilder.Entity("GestionIntApi.Models.TiendaApp", b =>
                {
                    b.HasOne("GestionIntApi.Models.Cliente", "Cliente")
                        .WithMany("TiendaApps")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionIntApi.Models.Tienda", "Tienda")
                        .WithMany("TiendaApps")
                        .HasForeignKey("TiendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Tienda");
                });

            modelBuilder.Entity("GestionIntApi.Models.Usuario", b =>
                {
                    b.HasOne("GestionIntApi.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("GestionIntApi.Models.Admin.MenuAdmin", b =>
                {
                    b.Navigation("MenuRolAdmins");
                });

            modelBuilder.Entity("GestionIntApi.Models.Admin.RolAdmin", b =>
                {
                    b.Navigation("MenuRolAdmins");

                    b.Navigation("UsuarioAdmins");
                });

            modelBuilder.Entity("GestionIntApi.Models.Cliente", b =>
                {
                    b.Navigation("Creditos");

                    b.Navigation("TiendaApps");
                });

            modelBuilder.Entity("GestionIntApi.Models.Credito", b =>
                {
                    b.Navigation("RegistrosPagos");
                });

            modelBuilder.Entity("GestionIntApi.Models.DetalleCliente", b =>
                {
                    b.Navigation("Cliente")
                        .IsRequired();
                });

            modelBuilder.Entity("GestionIntApi.Models.Menu", b =>
                {
                    b.Navigation("MenuRols");
                });

            modelBuilder.Entity("GestionIntApi.Models.Rol", b =>
                {
                    b.Navigation("MenuRols");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("GestionIntApi.Models.Tienda", b =>
                {
                    b.Navigation("ProductosActuales");

                    b.Navigation("TiendaApps");
                });

            modelBuilder.Entity("GestionIntApi.Models.Usuario", b =>
                {
                    b.Navigation("Cliente")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
